# Generated by Django 5.0.2 on 2025-05-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_branch_department_remove_choice_choice_text_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_candidate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='is_voter',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
