# Generated by Django 5.0.2 on 2025-05-13 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_candidate_is_candidate_voter_is_voter_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(default='Candidate', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.branch'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
