# Generated by Django 5.0.2 on 2025-05-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_candidate_department_alter_voter_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='srn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
