# Generated by Django 5.0.2 on 2025-05-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_poll_created_by_poll_delete_candidates_after_and_more'),
    ]

    operations = [
    ]
