# Generated by Django 5.0.2 on 2025-05-14 14:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20250514_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='delete_candidates_after',
        ),
        migrations.AlterField(
            model_name='poll',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.branch'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='department',
            field=models.CharField(blank=True, choices=[('Cultural', 'Cultural'), ('Technical', 'Technical'), ('President', 'President'), ('Vice President', 'Vice President'), ('Social', 'Social')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
