# Generated by Django 5.0.2 on 2025-05-16 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_poll_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='end_date',
        ),
    ]
